#!/bin/bash

set -e

function message_green  { echo -e "\e[1;36m==>\e[1;32m $1\e[0;0m" ; }
function message_red    { echo -e "\e[1;36m==>\e[1;31m $1\e[0;0m" ; }
function message_yellow { echo -e "\e[1;36m==>\e[1;33m $1\e[0;0m" ; }
function pkgbase {
    curl -s "https://aur.archlinux.org/rpc.php?type=info&arg=python2-pysqlite" \
        | python2 -m json.tool \
        | cat \
        | sed -n '/"PackageBase"/ { s/.*: "\(.*\)".*/\1/ ; p }'
}
function : { sudo -u ${BUILD_USER} $* ; }

. ${BUILD_AUR_CONF:-/etc/build-aur.conf}

BUILD_USER=${BUILD_USER:-aur}

ARCH=$(uname -m)
NAME=$(basename $REPO)

cat >/etc/sudoers.d/build-aur-$$ <<EOF
${BUILD_USER} ALL=(ALL) NOPASSWD: /usr/bin/pacman
EOF
trap "rm /etc/sudoers.d/build-aur-$$" EXIT

if [ ! -d "${BUILD}" ]; then
    message_red "[create] ${BUILD}"
    mkdir -pv "${BUILD}"
    chown "${BUILD_USER}" "${BUILD}"
    chmod 755 "${BUILD}"
fi

if [ ! -d "${REPO}" ]; then
    message_red "[create] ${REPO}"
    mkdir -pv "${REPO}"
    chown "${BUILD_USER}" "${REPO}"
    chmod 755 "${REPO}"
fi

if [ ! -f "${REPO}/${NAME}.db.tar.gz" ]; then
    message_red "[init] ${REPO}"
    : tar cvfT "${REPO}/${NAME}.db.tar.gz" /dev/null
    : ln -s "${NAME}.db.tar.gz" "${REPO}/${NAME}.db"
    pacman --sync --refresh
    pacman --sync --clean --noconfirm
fi

cd ${BUILD}
unclean=()
for (( i=0 ; i < ${#PKGS[*]} ; i++ )); do
    name="${PKGS[i]}"
    url="https://aur.archlinux.org/$(pkgbase $name).git"

    if [ ! -d "${name}" ]; then
        message_yellow "[clone] ${name} from ${url}"
        : git clone --origin aur ${url} ${name}
    fi
    cd "${name}"

    : git pull --rebase --verbose

    pkgver=$(sed -n '/^pkgver=/ s/pkgver=// p' "PKGBUILD")
    pkgrel=$(sed -n '/^pkgrel=/ s/pkgrel=// p' "PKGBUILD")

    [ -n "${pkgver}" ]
    [ -n "${pkgrel}" ]

    if [ -f ${REPO}/${name}-${pkgver}-${pkgrel}-*.pkg.tar.xz ]; then
        message_green "[skip] ${name}-${pkgver}-${pkgrel}"
    else
        message_yellow "[build] ${name}-${pkgver}-${pkgrel}"
        : makepkg --force --syncdeps --rmdeps --noconfirm --ignorearch
        : mv ${name}-${pkgver}-${pkgrel}*.pkg.tar.xz "${REPO}"
        : repo-add --new "${REPO}/${NAME}.db.tar.gz" ${REPO}/${name}-${pkgver}-${pkgrel}-*.pkg.tar.xz
        pacman --sync --refresh
    fi

    : git clean -dxf
    cd ..
done

pacman --sync --list --color=always ${NAME}
